
namespace Core.Models
{
    public enum BlockType /*: byte*/
    {
        Air = 0,
        Grass = 1,
        Stone = 2,
        Bedrock = 3,
        Break = 4,
        WoodLight = 5,
        WoodenLightBoards = 6,
        WoodenStaircase = 7, 
        WoodenChest = 8,
        CraftBlock = 9,
        Bake = 10,
        Water = 11,
        Black_Wool = 12,
        White_Wool = 13,
        Blue_Wool = 14,
        BlueLight_Wool = 15,
        Brown_Wool = 16,
        Green_Wool = 17,
        GreenLight_Wool = 18,
        Cake = 19,
        Coal_Ore = 20,
        Iron_Ore = 21,
        Gold_Ore = 22,
        Door_down = 23,
        Door_up = 24,
        CheetBlock = 25,
        Dirt = 26,
        LightCube = 27,
        Snow = 28,
        Cobblestone = 29,
        Ice = 30,
        IronDoor_down = 31,
        IronDoor_up = 32,
        Staircase = 33,
        Glass_White = 34,
        Watermelon = 35,
        BlackRed_Brick = 36,
        Red_Brick = 37,
        Obsidian = 38,
        Lamp_isOn = 39,
        Lamp_isOff = 40,
        OpenUpDoor = 41,
        Bush = 42,
        Cobblestone_Brick = 43,
        TNT = 44,
 

    }
}